Repository fairy-band/NewsLetter-Android, pull requests merged in 2025-07, with the labels that each got.

#4 [FEAT/#3] ISSUE 템플릿 만들기
  .github/ISSUE_TEMPLATE/issue-template.md
Labels: feature

#11 [FEAT/#9] 파이어베이스 연동
  .gitignore
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: feature

#14 [FEAT/13] 의존성 추가
  app/build.gradle.kts
  build.gradle.kts
  data/build.gradle.kts
  gradle/libs.versions.toml
  presentation/build.gradle.kts
Labels: feature

#25 Feat/24 홈 화면 UI 구현
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nexters/knownknowns/Application.kt
  app/src/main/java/com/nexters/knownknowns/KnownKnownsApplication.kt
  core/src/main/java/com/nexters/knownknowns/core/theme/Color.kt
  core/src/main/java/com/nexters/knownknowns/core/theme/Theme.kt
  core/src/main/java/com/nexters/knownknowns/core/theme/Type.kt
  data/build.gradle.kts
  data/src/main/java/com/nexters/knownknowns/data/di/DataModule.kt
  data/src/main/java/com/nexters/knownknowns/data/model/NewsResponse.kt
  data/src/main/java/com/nexters/knownknowns/data/repository/NewsRepository.kt
  data/src/main/java/com/nexters/knownknowns/data/repositoryimpl/NewsRepositoryImpl.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/nexters/knownknowns/presentation/MainActivity.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/di/PresentationModule.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/detail/DetailScreen.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/detail/DetailViewModel.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/HomeViewModel.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/model/NewsFeed.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/navigation/NavController.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/navigation/Screen.kt
  presentation/src/main/res/values/strings.xml
Labels: design

#29 [CHORE/28] 디자인 수정작업
  core/src/main/java/com/nexters/knownknowns/core/theme/Color.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/HomeScreen.kt
Labels: chore, design

#27 [DESIGN/22] 캐로셀 화면 구현
  core/src/main/java/com/nexters/knownknowns/core/designsystem/button/BaseButton.kt
  core/src/main/java/com/nexters/knownknowns/core/extension/Modifier.kt
  core/src/main/java/com/nexters/knownknowns/core/theme/Color.kt
  data/src/main/java/com/nexters/knownknowns/data/repositoryimpl/NewsRepositoryImpl.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/nexters/knownknowns/presentation/MainActivity.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/dialog/PopUpDialog.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/dialog/PopUpItem.kt
  presentation/src/main/res/drawable/ic_popup_dismiss.xml
  presentation/src/main/res/values/strings.xml
Labels: design

#32 Feat/26 AB 테스트 환경을 테스트하기 위한 코드를 작성했어요.
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/nexters/knownknowns/KnownKnownsApplication.kt
  data/build.gradle.kts
  data/src/main/java/com/nexters/knownknowns/data/repository/RemoteConfigRepository.kt
  data/src/main/java/com/nexters/knownknowns/data/repositoryimpl/NewsRepositoryImpl.kt
  data/src/main/java/com/nexters/knownknowns/data/repositoryimpl/RemoteConfigRepositoryImpl.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/HomeViewModel.kt
Labels: chore

#40 [FEAT] 원문 보기 버튼 클릭 시 웹으로 이어줘요.
  presentation/src/main/java/com/nexters/knownknowns/presentation/MainActivity.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/dialog/PopUpDialog.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/webview/WebViewScreen.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/navigation/Screen.kt
Labels: feature
