Repository fairy-band/NewsLetter-Android, pull requests merged in 2025-08, with the labels that each got.

#36 Feat/35 카드를 누르면 카드가 들썩거려요.
  core/src/main/AndroidManifest.xml
  core/src/main/java/com/nexters/knownknowns/core/extension/Context.kt
  core/src/main/java/com/nexters/knownknowns/core/extension/Modifier.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/dialog/PopUpDialog.kt
Labels: design

#43 [Design/42] 캐로셀 화면 수정
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/dialog/PopUpItem.kt
Labels: design

#53 Feat/52 컬러를 변경하는 AB테스트를 작성했어요.
  core/src/main/java/com/nexters/knownknowns/core/theme/Color.kt
  data/src/main/java/com/nexters/knownknowns/data/repository/RemoteConfigRepository.kt
  data/src/main/java/com/nexters/knownknowns/data/repositoryimpl/RemoteConfigRepositoryImpl.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/MainActivity.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/detail/DetailScreen.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/detail/DetailViewModel.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/CardColors.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/HomeViewModel.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/feature/home/dialog/PopUpDialog.kt
  presentation/src/main/java/com/nexters/knownknowns/presentation/navigation/Screen.kt
Labels: design

#61 Chore/60 내부 테스터 업로드 Fastlane 설치하기
  .github/workflows/internal-release.yml
  Gemfile
  Gemfile.lock
  README.md
  app/build.gradle.kts
  data/build.gradle.kts
  fastlane/.gitignore
  fastlane/Appfile
  fastlane/Fastfile
  fastlane/README.md
Labels: chore

#65 [Chore/62] 앱 로고 수정
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/drawable/ic_launcher_foreground.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-anydpi/ic_launcher.xml
  app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/ic_launcher_background.xml
Labels: chore

#67 [Feat/31] GA 로그 심기
  presentation/src/main/java/com/fairyband/soak/presentation/feature/home/HomeScreen.kt
  presentation/src/main/java/com/fairyband/soak/presentation/feature/home/dialog/PopUpDialog.kt
Labels: feature

#69 [Feat/68] 크래시리틱스 설정
  app/build.gradle.kts
  build.gradle.kts
  gradle/libs.versions.toml
Labels: feature

#72 Feat/64 알림 설정 바텀 시트를 구현했어요.
  app/src/main/AndroidManifest.xml
  core/src/main/java/com/fairyband/soak/core/extension/Context.kt
  data/src/main/java/com/fairyband/soak/data/datasource/AuthDataSource.kt
  data/src/main/java/com/fairyband/soak/data/datasource/NotificationDataSource.kt
  data/src/main/java/com/fairyband/soak/data/datasource/UserDataSource.kt
  data/src/main/java/com/fairyband/soak/data/di/ServiceModule.kt
  data/src/main/java/com/fairyband/soak/data/local/auth/AuthDataStore.kt
  data/src/main/java/com/fairyband/soak/data/local/user/UserDataStore.kt
  data/src/main/java/com/fairyband/soak/data/model/request/FcmRegisterRequest.kt
  data/src/main/java/com/fairyband/soak/data/model/response/RegisterResponse.kt
  data/src/main/java/com/fairyband/soak/data/remote/service/AuthService.kt
  data/src/main/java/com/fairyband/soak/data/remote/service/NotificationService.kt
  data/src/main/java/com/fairyband/soak/data/repository/AuthRepository.kt
  data/src/main/java/com/fairyband/soak/data/repository/NewsRepository.kt
  data/src/main/java/com/fairyband/soak/data/repository/NotificationRepository.kt
  data/src/main/java/com/fairyband/soak/data/repository/UserRepository.kt
  data/src/main/java/com/fairyband/soak/data/repositoryimpl/AuthRepositoryImpl.kt
  data/src/main/java/com/fairyband/soak/data/repositoryimpl/NewsRepositoryImpl.kt
  data/src/main/java/com/fairyband/soak/data/repositoryimpl/NotificationRepositoryImpl.kt
  data/src/main/java/com/fairyband/soak/data/repositoryimpl/UserRepositoryImpl.kt
  domain/src/main/java/com/fairyband/soak/domain/model/AuthInfo.kt
  domain/src/main/java/com/fairyband/soak/domain/usecase/RegisterOrLoginUseCase.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/fairyband/soak/presentation/feature/home/HomeScreen.kt
  presentation/src/main/java/com/fairyband/soak/presentation/feature/home/HomeViewModel.kt
  presentation/src/main/java/com/fairyband/soak/presentation/feature/home/bottomsheet/NotificationBottomSheet.kt
  presentation/src/main/java/com/fairyband/soak/presentation/service/SoakFirebaseMessagingService.kt
  presentation/src/main/res/drawable/symbol.xml
  presentation/src/main/res/values/strings.xml
Labels: feature
